image: golang:1.13.1-buster

.gobuild:
  stage: build
  before_script:
    - go version
  script:
    - make build

go1.11:build:
  image: golang:1.11-buster
  extends: .gobuild

go1.12:build:
  image: golang:1.12-buster
  extends: .gobuild

go1.13:build:
  image: golang:1.13-buster
  extends: .gobuild

go1.14:build:
  image: golang:1.14-buster
  extends: .gobuild

go1.15:build:
  image: golang:1.15-buster
  extends: .gobuild


.gotest:
  stage: test
  before_script:
    - go version
  script:
    - make cover

go1.11:test:
  needs:
    - go1.11:build
  image: golang:1.11-buster
  extends: .gotest

go1.12:test:
  needs:
    - go1.12:build
  image: golang:1.12-buster
  extends: .gotest

go1.13:test:
  needs:
    - go1.13:build
  image: golang:1.13-buster
  extends: .gotest

go1.14:test:
  needs:
    - go1.14:build
  image: golang:1.14-buster
  extends: .gotest

go1.15:test:
  needs:
    - go1.15:build
  image: golang:1.15-buster
  extends: .gotest


deploy_staging:
  stage: deploy
  needs:
    - go1.11:test
    - go1.12:test
    - go1.13:test
    - go1.14:test
    - go1.15:test
  only:
    refs:
      - dev
  before_script:
    - apt-get update -y && apt-get install xz-utils
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - make
    - tar -cJf file.tar.xz gosd data/
    - cat file.tar.xz | ssh ${USER_CLOUD_STAGING}@${HOST_CLOUD_STAGING} 'cd gosd/ && tar -xJf -'

