single_user: true
basic_auth: false
language: "en_US"
timezone: "Asia/Shanghai"
base_url: "http://localhost:8000/gosd/api/v3"
api_key: "15ce4017-4116-4caf-9302-04d0a1554daa"
secret: "15ce4017-4116-4caf-9302-04d0a1554daa"

