version: "3"
services:
  gosd:
    image: registry.gitlab.com/sbim/superdock/cloud/gosd/image:latest
    container_name: gosd
    command:
      - --debug
      - --noauth
    ports:
      - "8000:8000/tcp"
    environment:
      LISTEN_ADDR: '0.0.0.0:8000'
      REDIS_URL: 'redis://redis:6379/0'
      MQTT_URL: 'mqtt://admin:public@mqtt-broker:1883'
      DATABASE_URL: 'postgres://postgres:password@postgres/gosd?sslmode=disable'
    volumes:
      - ./data:/var/lib/gosd/data:ro
    depends_on:
      - redis
      - mosquitto
      - postgres
    restart: always

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379/tcp"

  mosquitto:
    image: eclipse-mosquitto:2.0.8
    container_name: mosquitto
    hostname: mqtt-broker
    command:
      - mosquitto
      - -c
      - /mosquitto.conf
    ports:
      - "1883:1883/tcp"
      - "8083:8083/tcp"
    volumes:
      - ./mosquitto.conf:/mosquitto.conf

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_DB: gosd
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - .db:/var/lib/postgresql/data

