version: "3"
services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379/tcp"

  mosquitto:
    image: eclipse-mosquitto:2.0.8
    container_name: mosquitto
    hostname: mqtt-broker
    command:
      - mosquitto
      - -c
      - /mosquitto-no-auth.conf
    ports:
      - "1883:1883/tcp"

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_DB: gosd
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - .db:/var/lib/postgresql/data

