version: "3"
services:
  redis:
    image: redis:6-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379/tcp"

  mosquitto:
    image: eclipse-mosquitto:2.0.8
    container_name: mosquitto
    hostname: mqtt-broker
    command:
      - mosquitto
      - -c
      - /mosquitto-no-auth.conf
    ports:
      - "1883:1883/tcp"

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_DB: gosd
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - .db:/var/lib/postgresql/data

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    hostname: swagger
    ports:
      - "8888:8080/tcp"
    environment:
      SWAGGER_JSON: "/app/openapi.json"
      BASE_URL: ""
    volumes:
      - ./swag/swagger.json:/app/openapi.json

networks:
  default:
    name: gosd

