openapi: 3.0.1
info:
  title: gosd
  description: 'superdock web service restful api'
  termsOfService: http://sb.im
  contact:
    email: sb@sb.im
  version: 3.0.0
servers:
- url: http://localhost:8000/gosd/api/v3
tags:
- name: blob
  description: file object
paths:
  /blobs:
    post:
      tags:
      - blob
      summary: Create a blob
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blob'

components:
  schemas:
    Blob:
      required:
      - file
      type: object
      properties:
        file:
          type: string
          example: "c5ulol594812rq77apfg"


