// Code generated by go generate; DO NOT EDIT.

package database // import "sb.im/gosd/database"

var SqlMap = map[string]string{
	"schema_version_1": `create table schema_version (
  version text not null
);

create extension if not exists hstore;

create table plans (
  id serial not null,
  name text not null,
  description text,
  node_id int not null,
  attachments hstore,
  create_at timestamp with time zone,
  update_at timestamp with time zone,
  primary key (id)
);

create table plan_logs (
  id bigserial not null,
  attachments hstore,
  create_at timestamp with time zone,
  update_at timestamp with time zone,

  primary key (id)
);

create table blobs (
  id bigserial not null,
  filename text,
  context text,
  checksum text,
  primary key (id)
);

`,
}

var SqlMapChecksums = map[string]string{
	"schema_version_1": "c5830f4d2039d609fdde0133412504d4509d7901ea0cde43ad9bca00a4a2017b",
}
